Removed tap-highlight-color from mobile Safari
csstools/sanitize.css pull request #179
Opened 2019-01-25 08:56 UTC by romapelypets

Webkit uses this tap color to highlight tapped form elements, links, and elements with various js events.
http://prntscr.com/mbxqwx
So, this rule removes this highlight.

2019-05-13 18:01 UTC, jonathantneal commented
Thank you for this, @romapelypets. Do you know if this CSS change has any impact on JS events otherwise?

2019-05-13 18:01 UTC, jonathantneal commented
If we can get this merged, I would like to add this to both sanitize.css and normalize.css.

2019-05-13 18:03 UTC, jonathantneal requested changes
Great work! We would just need to adjust the comment here to match the others. I’ve provided the desired change.

2019-05-13 18:03 UTC, jonathantneal commented on sanitize.css
> + * 6. Remove highlight when tapping links in mobile Safari
```suggestion
 * 6. Remove highlight when tapping links in iOS (opinionated).
```

2019-05-13 19:04 UTC, romapelypets commented
> Do you know if this CSS change has any impact on JS events otherwise?

No, it doesn't impact on JS events.

2019-05-13 19:04 UTC, romapelypets commented
> If we can get this merged, I would like to add this to both sanitize.css and normalize.css.

Yes, sure. You can add this rule

2019-05-14 19:34 UTC, jonathantneal commented
I would like to get this in. If you do not have time to fix the comment, I will make the change for you. I really appreciate you bringing this to my attention.

2019-05-17 06:19 UTC, jonathantneal commented
Since I had not heard back, I am closing this in favor of #187

2019-05-17 06:19 UTC, closed without merging