Remove arrow from <select> using 'size' or 'multiple' attribute
csstools/sanitize.css pull request #192
Opened 2019-07-04 10:52 UTC by alexandersandberg

This will remove the arrow symbol from <select> elements using either the 'size'
or the 'multiple' attribute, since these are expanded and using a scrollbar instead.

See [this Codepen](https://codepen.io/alexandersandberg/pen/NZBNKo) for a live preview of the old vs. the new styling. Preview image below.

![Codepen preview of fix](https://user-images.githubusercontent.com/35671299/60661423-29f9e900-9e5a-11e9-8a89-8776d2bfd3ab.png)

2019-07-11 11:55 UTC, jonathantneal approved these changes

2019-07-11 12:15 UTC, jonathantneal requested changes
This is a fantastic PR, @alexandersandberg. Thank you for the clear description and the reduced test case.

I would like to make 2 adjustments, in order to keep as much styling in the least specific selector.

2019-07-11 12:15 UTC, jonathantneal commented on forms.css
> -  background: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='4'%3E%3Cpath d='M4 0h6L7 4'/%3E%3C/svg%3E") no-repeat right center / 1em;
I would like to make 2 adjustments. This is the first adjustment I would like to make, in order to keep as much styling in the least specific selector:

```suggestion
  background: no-repeat right center / 1em;
```

2019-07-11 12:15 UTC, jonathantneal commented on forms.css
> +  background: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='4'%3E%3Cpath d='M4 0h6L7 4'/%3E%3C/svg%3E") no-repeat right center / 1em;
This is the other adjustment I would like to make, in order to keep as much styling in the least specific selector:

```suggestion
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='4'%3E%3Cpath d='M4 0h6L7 4'/%3E%3C/svg%3E");
```

2019-07-11 12:43 UTC, jonathantneal approved these changes

2019-07-11 12:44 UTC, merged

2019-07-11 12:45 UTC, alexandersandberg commented
These adjustments look great, @jonathantneal! I have pushed a fix to the branch (as you've noticed already, hehe). 🙂

2019-07-11 12:46 UTC, jonathantneal commented
Your work has been merged! I’ll ping you shortly when the next release is published.

2019-07-11 12:55 UTC, jonathantneal commented
Published via sanitize.css@11.0.0! 🎉

2019-07-11 13:00 UTC, alexandersandberg commented
Yay! Happy to help out. 😄

2021-02-03 15:00 UTC, goodpixels commented
This method is not great because the selector is too specific and I need to write even more specific selectors in my CSS to amend the styling of the select input.

`select:not([multiple]):not([size])` takes precedence over the most commonly used selectors, such as, but not limited to:

```
select.custom-select
.custom-select select
```

You can see an example Codepen here: https://codepen.io/goodpixels/pen/RwoWpgV

I think this needs to be re-visited and possibly the selector should be changed to a custom CSS class name.

Thank you!

2021-02-04 02:52 UTC, tigt commented
It might even be misguided beyond that, since [on mobile OS’s adding `size` or `multiple` does not make the `<select>`s expand into listboxes](https://stackoverflow.com/questions/13994432/multi-select-select-box-on-mobile-devices).

2021-02-04 11:33 UTC, goodpixels commented
I think in this case this should do the trick:

```
select {
    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='4'%3E%3Cpath d='M4 0h6L7 4'/%3E%3C/svg%3E");
}

select[multiple] {
    background-image: none;
    // Alternatively background-size
    // background-size: 0;
}
```